Repository Andre-Martin/GoodGame, pull requests merged in 2024-03, with the labels that each got.

#66 Jina
  Discussions/integration test candidates.jpg
  Discussions/unit test candidates.jpg
  src/pages/Home.tsx
Labels: documentation

#67 created redux-slice for chat component, added additional parser for t…
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/ChatBox.tsx
  src/components/ChatCard.tsx
  src/css/sketchy.css
  src/features/boardgame/boardgameSlice.ts
  src/features/boardgamelist/boardgameListSlice.ts
  src/features/chat/chatSlice.ts
  src/features/store.ts
  src/main.tsx
  src/pages/Chat.tsx
  src/pages/GameList.tsx
  src/pages/Home.tsx
  src/pages/SingleGame.tsx
  src/test/my-component.test.ts
  src/utils/ROUTES.ts
  src/utils/boardgameAPI.ts
  src/utils/common.ts
  src/utils/mockInfo.ts
  src/utils/types.ts
Labels: enhancement

#69 Added regex
  package-lock.json
  package.json
  src/components/ChatBox.tsx
  src/components/Footer.tsx
  src/components/GameListItem.tsx
  src/features/hooks/redux.hooks.ts
  src/features/store.ts
  src/main.tsx
  src/pages/Chat.tsx
  src/pages/SingleGame.tsx
  src/tests/App.test.tsx
  src/tests/BoardgamePage.test.tsx
  src/tests/setup.ts
  src/utils/common.ts
  src/utils/test-utils.tsx
  vite.config.ts
Labels: enhancement

#72 Fixed merge conflicts
  src/components/ChatBox.tsx
  src/components/GameListItem.tsx
  src/features/store.ts
  src/pages/HotBGList.tsx
  src/pages/SearchBGList.tsx
  src/utils/common.ts
Labels: bug

#74 used clearText function in the components
  src/components/GameListItem.tsx
  src/components/Header.tsx
  src/pages/SearchBGList.tsx
  src/pages/SingleGame.tsx
  src/utils/common.ts
Labels: enhancement

#75 Added meeting minutes to Documents
  docs/Documents/Meetings/meetingFeb1.docx
  docs/Documents/Meetings/meetingFeb10.docx
  docs/Documents/Meetings/meetingFeb15.docx
  docs/Documents/Meetings/meetingFeb3.docx
  docs/Documents/Meetings/meetingJan26.docx
  docs/Documents/Meetings/meetingJan27.docx
  docs/Documents/Meetings/meetingMar11.docx
  docs/Documents/Meetings/meetingMar14.docx
  docs/Documents/Meetings/meetingMar21.docx
  docs/Documents/Meetings/meetingMar7.docx
Labels: documentation

#76 Added PDF versions of meeting minutes to Documenents
  docs/Documents/Meetings/meetingFeb1.docx
  docs/Documents/Meetings/meetingFeb1.pdf
  docs/Documents/Meetings/meetingFeb10.docx
  docs/Documents/Meetings/meetingFeb10.pdf
  docs/Documents/Meetings/meetingFeb15.docx
  docs/Documents/Meetings/meetingFeb15.pdf
  docs/Documents/Meetings/meetingFeb3.docx
  docs/Documents/Meetings/meetingFeb3.pdf
  docs/Documents/Meetings/meetingJan26.docx
  docs/Documents/Meetings/meetingJan26.pdf
  docs/Documents/Meetings/meetingJan27.docx
  docs/Documents/Meetings/meetingJan27.pdf
  docs/Documents/Meetings/meetingMar11.docx
  docs/Documents/Meetings/meetingMar11.pdf
  docs/Documents/Meetings/meetingMar14.docx
  docs/Documents/Meetings/meetingMar14.pdf
  docs/Documents/Meetings/meetingMar21.docx
  docs/Documents/Meetings/meetingMar21.pdf
  docs/Documents/Meetings/meetingMar7.docx
  docs/Documents/Meetings/meetingMar7.pdf
Labels: documentation

#77 Create ci.yml
  .github/workflows/ci.yml
Labels: enhancement
