Repository Andre-Martin/GoodGame, pull requests merged in 2024-04, with the labels that each got.

#82 Completed UI of the project
  frontend/src/components/HotBGList/HotListItem.tsx
  frontend/src/components/HotList/HotListItem.tsx
  frontend/src/components/ListItemFlex.tsx
  frontend/src/components/Pagination.tsx
  frontend/src/components/RatingIcon.tsx
  frontend/src/components/SingleGame/CredPanel/CredPanel.tsx
  frontend/src/components/SingleGame/CredPanel/CredPanelItem.tsx
  frontend/src/components/SingleGame/InfoPanel/InfoPanel.tsx
  frontend/src/components/SingleGame/MainPanel/MainPanel.tsx
  frontend/src/components/SingleGame/MainPanel/index.ts
  frontend/src/components/SingleGame/TabPanel/CommentTab/CommentTab.tsx
  frontend/src/components/SingleGame/TabPanel/CommentTab/CommentTabItem.tsx
  frontend/src/components/SingleGame/TabPanel/MPTab/MarketPlaceTabItem.tsx
  frontend/src/components/SingleGame/TabPanel/MPTab/MarketplaceTab.tsx
  frontend/src/components/SingleGame/TabPanel/StatTab/StatTab.tsx
  frontend/src/components/SingleGame/TabPanel/TabPanel.tsx
  frontend/src/components/SingleGame/TabPanel/VideoTab/VideoTab.tsx
  frontend/src/components/SingleGame/TabPanel/VideoTab/VideoTabItem.tsx
  frontend/src/components/SingleGame/index.ts
  frontend/src/components/TextNotFound.tsx
  frontend/src/css/styles.css
  frontend/src/features/slices/boardgameListSlice.ts
  frontend/src/features/slices/boardgameSlice.ts
  frontend/src/features/slices/hotListSlice.ts
  frontend/src/features/store.ts
  frontend/src/img/chatgpt.png
  frontend/src/pages/Home.tsx
  frontend/src/pages/HotList.tsx
  frontend/src/pages/Page404.tsx
  frontend/src/pages/SingleGame.tsx
  frontend/src/utils/parser.ts
  frontend/src/utils/theme.ts
  frontend/src/utils/types.ts
Labels: enhancement

#93 Added configs for deployment
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/App/Header.tsx
  frontend/src/components/SearchBGList/SearchListItem.tsx
  frontend/src/components/SingleGame/MainPanel/MainPanel.tsx
  frontend/src/pages/Home.tsx
  frontend/vite.config.ts
Labels: documentation, enhancement

#94 Create deploy yml file
  .github/workflows/deploy
Labels: documentation, enhancement

#95 dev
  .github/workflows/jekyll-gh-pages.yml
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/App/Footer.tsx
  src/components/App/Header.tsx
  src/components/App/HeaderLink.tsx
  src/components/Home/HomeImage.tsx
  src/components/Home/styles.css
  src/components/SingleGame/CredPanel/CredPanelItem.tsx
  src/components/SingleGame/InfoPanel/InfoPanel.tsx
  src/features/hooks/uiHooks.ts
  src/img/blueGuy.jpg
  src/img/logo.png
  src/pages/Home.tsx
  src/pages/SingleGame.tsx
  src/utils/common.ts
  src/utils/theme.ts
  tsconfig.json
  vite.config.ts
Labels: documentation, enhancement

#96 Added meeting minutes, AI Declaration, adjusted README file with upda…
  README.md
  docs/Documents/GoodGame_Project_Report.pdf
Labels: documentation
